export const ADD_AVAILABLE_TIMEZONE = 'ADD_AVAILABLE_TIMEZONE'
export const ADD_SHOWN_TIMEZONE = 'ADD_SHOWN_TIMEZONE'
export const REMOVE_SHOWN_TIMEZONE = 'REMOVE_SHOWN_TIMEZONE'
export const CLEAR_SHOWN_TIMEZONES = 'CLEAR_SHOWN_TIMEZONES'
